#redis配置
spring:
  redis:
    database: 2
    host: 47.102.99.184
    port: 6379
    password: wjh_redis123.
    lettuce:
      pool:
        # 接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
    # 连接超时时间
    timeout: 2000ms
