server:
  port: 18802
  servlet:
    context-path: /boss-note

spring:
  application:
    name: boss-note
  profiles:
    active: debug
  jndi:
    ignore: true

logging:
  config: ${user.dir}/config/logConfig.xml
  path: ${user.dir}
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1201/eureka
#  instance:
#    instance-id: boss-system-18801

# 配置监控信息
info:
  app.name: boss-note
  company.name: wjh_q@163.com

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic